apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tef3j0i54-nodejs-gitops
  description: This is GitOps manifest for tef3j0i54-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=tef3j0i54-nodejs
    backstage.io/kubernetes-id: tef3j0i54-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tef3j0i54-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tef3j0i54-nodejs
