apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tef3j0i54-nodejs
  janus-idp.io/tekton: tef3j0i54-nodejs
  backstage.io/kubernetes-id: tef3j0i54-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tef3j0i54-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
