apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tef3j0i54-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tef3j0i54-nodejs 
  name: tef3j0i54-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tef3j0i54-nodejs 
