apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tef3j0i54-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:786effeb8b06e93d8c8cfdb0553bbdeb4728103c@sha256:f7c061fc0fa0d45e0cdfb651847863a64d7a9f115197561b12088febfd2b8ecb
          name: container-image
